/**
 * XPath Generator for Node.js/Playwright context.
 *
 * This module provides utilities for generating XPath selectors by injecting
 * browser-side code via Playwright's evaluate().
 *
 * The browser bundle is built separately via `bun run build:xpath` and loaded
 * at runtime for injection into Playwright pages.
 *
 * For unit testing with JSDOM, import directly from browser/index.ts.
 */

import { readFile } from "fs/promises";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

import type { SelectorResult, XPathGeneratorConfig } from "./types.js";
import { DEFAULT_CONFIG } from "./xpath.config.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

/**
 * Load the browser bundle script.
 * The bundle is an IIFE that creates `window.__xpathBundle` with all exports.
 */
let _bundleScript: string | null = null;

/**
 * Get the browser bundle script for injection via page.addInitScript().
 */
export async function getBrowserBundle(): Promise<string> {
  if (_bundleScript === null) {
    const bundlePath = join(__dirname, "browser-generator.bundle.js");
    _bundleScript = await readFile(bundlePath, "utf-8");
  }
  return _bundleScript;
}

/**
 * Normalize a string for config comparison (lowercase, trimmed).
 * Returns null for non-strings.
 */
function normalizeConfigString(s: unknown): string | null {
  if (typeof s !== "string") {
    return null;
  }
  const normalized = s.trim().toLowerCase();
  return normalized || null;
}

/**
 * Validate and sanitize config before passing to browser.
 * Only whitelisted fields are included to prevent unexpected properties.
 * Strings are normalized to lowercase to match tagName.toLowerCase() comparisons.
 */
export function sanitizeConfig(
  config: XPathGeneratorConfig,
): XPathGeneratorConfig {
  // Whitelist only known fields - prevents embedding unexpected properties
  // Normalize string arrays to lowercase for case-insensitive matching
  return {
    maxTextLength: Number(config.maxTextLength) || 50,
    maxDepth: Number(config.maxDepth) || 50,
    minHrefLength: Number(config.minHrefLength) || 2,
    maxHrefLength: Number(config.maxHrefLength) || 100,
    textTags: Array.isArray(config.textTags)
      ? (config.textTags.map(normalizeConfigString).filter(Boolean) as string[])
      : [],
    containerTags: Array.isArray(config.containerTags)
      ? (config.containerTags
          .map(normalizeConfigString)
          .filter(Boolean) as string[])
      : [],
    landmarkTags: Array.isArray(config.landmarkTags)
      ? (config.landmarkTags
          .map(normalizeConfigString)
          .filter(Boolean) as string[])
      : [],
    landmarkRoles: Array.isArray(config.landmarkRoles)
      ? (config.landmarkRoles
          .map(normalizeConfigString)
          .filter(Boolean) as string[])
      : [],
    testIdAttrs: Array.isArray(config.testIdAttrs)
      ? config.testIdAttrs.filter((t) => typeof t === "string")
      : [], // Don't lowercase - these are attribute names, not tags
  };
}

/**
 * Get sanitized default config.
 */
export function getDefaultConfig(): XPathGeneratorConfig {
  return sanitizeConfig(DEFAULT_CONFIG);
}

// ==========================================================================
// Bundle Types (for TypeScript in browser context)
// ==========================================================================

/**
 * Type declaration for the browser bundle global.
 * Use with: declare const __xpathBundle: XPathBundle;
 */
export interface XPathBundle {
  browserXPathGenerator: (
    el: Element,
    config: XPathGeneratorConfig,
  ) => SelectorResult;
  escapeAttr: (val: string) => string;
  scopeXPath: (prefix: string, suffix: string) => string;
  normalizeSpace: (str: string | null | undefined) => string | null;
  isAutoGeneratedId: (id: string) => boolean;
  scoreAnchorId: (id: string) => number;
  isDynamicUrl: (url: string) => boolean;
}

/**
 * Type for the XPath bundle in browser context.
 */
export type XPathBundleFunctions = {
  browserXPathGenerator: (
    el: Element,
    config: XPathGeneratorConfig,
  ) => SelectorResult;
};

/**
 * Browser-side function that ensures the XPath bundle is loaded.
 * This is serialized and sent to the browser - do not use closures.
 *
 * NOTE: Uses Function constructor intentionally for cross-context serialization.
 * This is a standard pattern for Playwright browser injection where we need to
 * load code into a separate JavaScript context (the browser). The bundle script
 * is controlled by us (built from our source), not user input.
 */
function ensureXPathBundleInBrowser(
  bundleScript: string,
): XPathBundleFunctions {
  const win = window as Window & { __xpathBundle?: XPathBundleFunctions };
  if (!win.__xpathBundle) {
    // Function constructor is used intentionally here to execute the bundle
    // in the browser context. The bundleScript is our own code, not user input.
    const FunctionConstructor = Function;
    win.__xpathBundle = FunctionConstructor(
      bundleScript + "; return __xpathBundle;",
    )() as XPathBundleFunctions;
  }
  return win.__xpathBundle;
}

/**
 * Creates a Playwright page.evaluate helper with XPath bundle injection.
 * Use this to run custom code in the browser with access to the XPath generator.
 */
export async function createXPathEvaluator(page: {
  evaluate: (
    fn: (args: {
      bundle: string;
      cfg: XPathGeneratorConfig;
      ensureFn: string;
      evalFn: string;
      data: unknown;
    }) => unknown,
    args: unknown,
  ) => Promise<unknown>;
}) {
  const bundle = await getBrowserBundle();
  const config = getDefaultConfig();
  const ensureFnStr = ensureXPathBundleInBrowser.toString();

  return function evaluateWithXPath<T, D = undefined>(
    fn: (
      xpathBundle: XPathBundleFunctions,
      cfg: XPathGeneratorConfig,
      data: D,
    ) => T,
    data?: D,
  ): Promise<T> {
    return page.evaluate(
      (args: {
        bundle: string;
        cfg: XPathGeneratorConfig;
        ensureFn: string;
        evalFn: string;
        data: D;
      }) => {
        // Function constructor used intentionally for browser code injection
        const FunctionConstructor = Function;
        const ensureBundle = FunctionConstructor(
          "return " + args.ensureFn,
        )() as typeof ensureXPathBundleInBrowser;
        const xpathBundle = ensureBundle(args.bundle);
        const evalFn = FunctionConstructor(
          "return " + args.evalFn,
        )() as typeof fn;
        return evalFn(xpathBundle, args.cfg, args.data);
      },
      {
        bundle,
        cfg: config,
        ensureFn: ensureFnStr,
        evalFn: fn.toString(),
        data: data as D,
      },
    ) as Promise<T>;
  };
}

// Re-export the direct functions (for Node.js/JSDOM testing)
export { browserXPathGenerator } from "./browser/index.js";
