/**
 * XPath Generation Module
 *
 * Provides utilities for generating unique XPath selectors for DOM elements.
 * Used by the element detection service to create stable selectors for
 * identified interactive elements.
 *
 * ## Architecture
 *
 * The module has two execution contexts:
 * 1. **Node.js/Bun** - Configuration, bundle loading, Playwright integration
 * 2. **Browser** - Actual XPath generation (runs via Playwright evaluate())
 *
 * ## Security
 *
 * The `escapeXPathAttribute` function is critical for preventing XPath injection.
 * All user-provided values MUST be escaped before embedding in XPath expressions.
 *
 * ## Usage
 *
 * ```typescript
 * import { escapeXPathAttribute, scopeXPath, DEFAULT_CONFIG } from './xpath';
 *
 * // Escape user input for XPath
 * const escaped = escapeXPathAttribute(userInput);
 * const xpath = `//button[@aria-label=${escaped}]`;
 *
 * // Scope an XPath within a landmark
 * const scoped = scopeXPath('//header', 'button');
 * // -> '//header//button'
 * ```
 */

// Types
export type {
  XPathGeneratorConfig,
  BrowserCtx,
  ExtractedData,
  Strategy,
  StrategyRunner,
  RichSelectorResult,
  NoSelectorResult,
  SelectorResult,
  SelectorScope,
  NoSelectorReason,
} from "./types.js";

// Configuration
export { DEFAULT_CONFIG } from "./xpath.config.js";

// Shared utilities (work in both Node.js and browser)
export {
  escapeXPathAttribute,
  scopeXPath,
  isDynamicUrl,
  DYNAMIC_QUERY_KEYS,
  DYNAMIC_KEY_PREFIXES,
} from "./shared.js";

// Generator utilities
export {
  sanitizeConfig,
  getDefaultConfig,
  getBrowserBundle,
  createXPathEvaluator,
  browserXPathGenerator,
  type XPathBundle,
  type XPathBundleFunctions,
} from "./generator.js";

// Browser-side utilities (for direct use or testing)
export { isAutoGeneratedId } from "./browser/scope-utils.js";
export { scoreAnchorId } from "./browser/anchors.js";
export { normalizeSpace } from "./browser/extract.js";
