import { describe, it, expect } from "bun:test";
import {
  escapeXPathAttribute,
  scopeXPath,
  isDynamicUrl,
  isAutoGeneratedId,
  scoreAnchorId,
  DEFAULT_CONFIG,
} from "./index.js";

describe("XPath utilities", () => {
  describe("escapeXPathAttribute", () => {
    it("escapes simple strings", () => {
      expect(escapeXPathAttribute("hello")).toBe('"hello"');
    });

    it("escapes strings with double quotes", () => {
      expect(escapeXPathAttribute('say "hello"')).toBe("'say \"hello\"'");
    });

    it("escapes strings with single quotes", () => {
      expect(escapeXPathAttribute("it's good")).toBe('"it\'s good"');
    });

    it("escapes strings with both quotes using concat", () => {
      const result = escapeXPathAttribute('it\'s "complex"');
      expect(result).toContain("concat");
    });

    it("handles empty string values", () => {
      expect(escapeXPathAttribute("")).toBe('""');
    });

    it("handles special XML characters in values", () => {
      // These should be properly escaped within quotes
      expect(escapeXPathAttribute("<div>")).toBe('"<div>"');
      expect(escapeXPathAttribute("a&b")).toBe('"a&b"');
    });

    // Security-critical: XPath injection prevention
    it("prevents XPath injection via quotes - double quotes only", () => {
      // Malicious input attempting to break out of double quotes
      const malicious = '"] | //password | //*["';
      const escaped = escapeXPathAttribute(malicious);
      // Should wrap in single quotes since input has double quotes but no single quotes
      expect(escaped).toBe("'\"] | //password | //*[\"'");
      // The XPath engine will treat the entire thing as a literal string
    });

    it("prevents XPath injection via mixed quotes", () => {
      // Malicious input with both quote types - truly attempts to break out
      const malicious = "'] | //password | //*['\"";
      const escaped = escapeXPathAttribute(malicious);
      // Should use concat() since it has both quote types
      expect(escaped).toContain("concat");
    });

    it("handles values starting with double quote", () => {
      const result = escapeXPathAttribute('"starts');
      // Only has double quotes, so wrap in single quotes
      expect(result).toBe("'\"starts'");
    });

    it("handles consecutive mixed quotes", () => {
      const result = escapeXPathAttribute("test'\"'test");
      expect(result).toContain("concat");
    });
  });

  describe("scopeXPath", () => {
    it("scopes XPath with prefix", () => {
      expect(scopeXPath("//header", "button")).toBe("//header//button");
    });

    it("handles empty prefix", () => {
      expect(scopeXPath("", "button")).toBe("//button");
    });

    it("strips leading // from suffix", () => {
      expect(scopeXPath("//header", "//a")).toBe("//header//a");
    });

    it("wraps union prefixes in parentheses", () => {
      expect(scopeXPath("//header | //nav", "a")).toBe("(//header | //nav)//a");
    });

    it("does not double-wrap already wrapped unions", () => {
      expect(scopeXPath("(//header | //nav)", "a")).toBe("(//header | //nav)//a");
    });
  });

  describe("isDynamicUrl", () => {
    it("returns false for URLs without query strings", () => {
      expect(isDynamicUrl("/about")).toBe(false);
      expect(isDynamicUrl("https://example.com")).toBe(false);
    });

    it("returns false for stable query params", () => {
      expect(isDynamicUrl("/search?q=test")).toBe(false);
      expect(isDynamicUrl("/page?id=123")).toBe(false);
    });

    it("returns true for session/auth tokens", () => {
      expect(isDynamicUrl("/page?session=abc123")).toBe(true);
      expect(isDynamicUrl("/page?token=xyz")).toBe(true);
      expect(isDynamicUrl("/page?jwt=eyJhbGciOiJI")).toBe(true);
    });

    it("returns true for tracking parameters", () => {
      expect(isDynamicUrl("/page?utm_source=google")).toBe(true);
      expect(isDynamicUrl("/page?fbclid=abc123")).toBe(true);
      expect(isDynamicUrl("/page?gclid=xyz789")).toBe(true);
    });

    it("returns true for cache busters", () => {
      expect(isDynamicUrl("/page?_=1702396800")).toBe(true);
      expect(isDynamicUrl("/page?nocache=1")).toBe(true);
    });

    it("handles custom denylist", () => {
      expect(isDynamicUrl("/page?custom=abc")).toBe(false);
      expect(isDynamicUrl("/page?custom=abc", ["custom"])).toBe(true);
    });
  });

  describe("isAutoGeneratedId", () => {
    it("returns true for UUIDs", () => {
      expect(isAutoGeneratedId("550e8400-e29b-41d4-a716-446655440000")).toBe(true);
    });

    it("returns true for numeric IDs", () => {
      expect(isAutoGeneratedId("12345")).toBe(true);
    });

    it("returns true for React generated IDs", () => {
      expect(isAutoGeneratedId(":r0:")).toBe(true);
      expect(isAutoGeneratedId("react-aria-123")).toBe(true);
    });

    it("returns false for semantic IDs", () => {
      expect(isAutoGeneratedId("main-content")).toBe(false);
      expect(isAutoGeneratedId("submit-button")).toBe(false);
    });

    it("returns false for short readable IDs", () => {
      expect(isAutoGeneratedId("header")).toBe(false);
      expect(isAutoGeneratedId("nav")).toBe(false);
    });
  });

  describe("scoreAnchorId", () => {
    it("returns 0 for auto-generated IDs", () => {
      expect(scoreAnchorId(":r0:")).toBe(0);
      expect(scoreAnchorId("12345")).toBe(0);
    });

    it("returns positive score for semantic IDs", () => {
      expect(scoreAnchorId("main-content")).toBeGreaterThan(0.5);
      expect(scoreAnchorId("user-profile")).toBeGreaterThan(0.5);
    });

    it("returns higher score for hyphenated readable IDs", () => {
      const hyphenated = scoreAnchorId("main-content");
      const simple = scoreAnchorId("content");
      expect(hyphenated).toBeGreaterThan(simple);
    });
  });

  describe("DEFAULT_CONFIG", () => {
    it("has reasonable default config", () => {
      expect(DEFAULT_CONFIG.maxTextLength).toBeGreaterThan(0);
      expect(DEFAULT_CONFIG.testIdAttrs).toContain("data-testid");
    });

    it("includes common test ID attributes", () => {
      expect(DEFAULT_CONFIG.testIdAttrs).toContain("data-testid");
      expect(DEFAULT_CONFIG.testIdAttrs).toContain("data-test");
      expect(DEFAULT_CONFIG.testIdAttrs).toContain("data-cy");
    });

    it("includes semantic landmark tags", () => {
      expect(DEFAULT_CONFIG.landmarkTags).toContain("header");
      expect(DEFAULT_CONFIG.landmarkTags).toContain("main");
      expect(DEFAULT_CONFIG.landmarkTags).toContain("nav");
    });
  });
});
