import type { BrowserCtx } from "./types.js";
import { isAutoGeneratedId } from "./scope-utils.js";
import { escapeAttr } from "./xpath-utils.js";

/**
 * Score an anchor candidate for stability.
 * Higher score = more likely to be stable.
 * Returns 0 if the anchor should be skipped entirely.
 *
 * Score ranges:
 * - 0: Auto-generated, skip entirely
 * - 0.5: Basic non-autogenerated ID
 * - 0.7+: Good ID (readable patterns, short)
 * - 0.9+: Excellent ID, use immediately
 */
export function scoreAnchorId(id: string): number {
  if (isAutoGeneratedId(id)) {
    return 0;
  }

  let score = 0.5;

  // Prefer hyphen-separated readable IDs: user-profile, main-content
  if (/^[a-z][a-z0-9]*(-[a-z0-9]+)+$/i.test(id)) {
    score += 0.3;
  }

  // Short, simple IDs are usually intentional
  if (id.length <= 20 && /^[a-zA-Z][a-zA-Z0-9_-]*$/.test(id)) {
    score += 0.1;
  }

  // Penalize IDs with numbers at the end (often indexed)
  if (/\d+$/.test(id) && !/^(h[1-6]|item\d+)$/i.test(id)) {
    score -= 0.2;
  }

  return Math.max(0, score);
}

/**
 * Find a stable ancestor element to use as a scoping anchor.
 *
 * Unlike landmarks, anchors are any element with a stable ID or test-id.
 * They provide fallback scoping when no landmark is available.
 */
export function findAnchorAncestor(
  element: Element,
  ctx: BrowserCtx,
  isUnique: (xpath: string) => boolean,
): string | null {
  let current = element.parentElement;
  let depth = 0;

  // Track best anchor found (prefer higher-scored IDs)
  let bestAnchor: { xpath: string; score: number } | null = null;

  while (
    current &&
    current !== ctx.document.body &&
    current !== ctx.document.documentElement &&
    depth < ctx.config.maxDepth
  ) {
    depth++;

    // Check test IDs first (always preferred - they're explicitly for testing)
    for (const attr of ctx.config.testIdAttrs) {
      const val = current.getAttribute(attr);
      if (val) {
        const anchorXpath = "//*[@" + attr + "=" + escapeAttr(val) + "]";
        if (isUnique(anchorXpath)) {
          // Test IDs are best - return immediately
          return anchorXpath;
        }
      }
    }

    // Check ID with scoring
    const id = current.id;
    if (id) {
      const score = scoreAnchorId(id);
      if (score > 0) {
        const anchorXpath = "//*[@id=" + escapeAttr(id) + "]";
        if (isUnique(anchorXpath)) {
          // High-quality IDs (semantic + readable patterns) return immediately
          // Lower-scored IDs are tracked but we keep looking for better
          if (score >= 0.9) {
            return anchorXpath;
          }
          // Otherwise track as candidate but keep looking for better
          if (!bestAnchor || score > bestAnchor.score) {
            bestAnchor = { xpath: anchorXpath, score };
          }
        }
      }
    }

    current = current.parentElement;
  }

  // Return best anchor found (may be lower-scored but still usable)
  return bestAnchor ? bestAnchor.xpath : null;
}
