/**
 * Browser-side XPath Generator - Bundle Entrypoint
 *
 * This file is the entrypoint for browser bundling. It exports the public API
 * that will be available in the browser via the __xpathBundle global.
 */

// Re-export public functions
export { browserXPathGenerator } from "./core.js";

// Re-export public types
export type {
  XPathGeneratorConfig,
  BrowserCtx,
  ExtractedData,
  Strategy,
  StrategyRunner,
  RichSelectorResult,
  NoSelectorResult,
  SelectorResult,
} from "./types.js";

// Re-export utilities that may be useful for testing
export { escapeAttr, scopeXPath } from "./xpath-utils.js";
export { normalizeSpace } from "./extract.js";
export { isAutoGeneratedId, isDynamicUrl } from "./scope-utils.js";
export { scoreAnchorId } from "./anchors.js";
