import type { BrowserCtx } from "./types.js";
import { escapeAttr } from "./xpath-utils.js";
import { isDynamicUrl } from "../shared.js";

// Re-export isDynamicUrl for consumers that expect it from this module
export { isDynamicUrl };

/** Maximum reasonable length for a human-authored ID */
const MAX_REASONABLE_ID_LENGTH = 50;

/**
 * Options for resolving an element to a unique XPath.
 */
export interface ResolveOptions {
  /** Tag name to use in xpath ('main', 'nav') or '*' for any element */
  tag: string;
  /** Try aria-label attribute */
  tryAriaLabel?: boolean;
  /** Try role attribute */
  tryRole?: boolean;
  /** Fall back to positional index if no unique selector found */
  positionalFallback?: boolean;
}

/**
 * Check if an ID looks auto-generated and should be avoided.
 * Auto-generated IDs are unstable (change between page loads/builds).
 */
export function isAutoGeneratedId(id: string): boolean {
  // Empty or whitespace-only
  if (!id || !id.trim()) {
    return true;
  }

  // UUID pattern: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  if (
    /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id)
  ) {
    return true;
  }

  // Purely numeric IDs (often auto-incremented)
  if (/^\d+$/.test(id)) {
    return true;
  }

  // React generated IDs: :r0:, :R0:
  if (/^:[rR]\d+:?$/.test(id)) {
    return true;
  }

  // React Aria generated IDs: react-aria-123 (anchored to purely numeric suffix)
  // Allows: react-aria-Menu (could be intentional)
  // Rejects: react-aria-123, react-aria-1
  if (/^react-aria-\d+$/.test(id)) {
    return true;
  }

  // Radix UI generated IDs: radix-:r0:, radix-123 (only numeric/internal patterns)
  // Allows: radix-menu, radix-dialog (could be intentional custom IDs)
  // Rejects: radix-:r0:, radix-123, radix-R1
  if (/^radix-[:\d]/.test(id)) {
    return true;
  }

  // Angular generated IDs: ng-*, ngcontent-*, _ngcontent-*
  if (/^_?ng(content)?-/.test(id)) {
    return true;
  }

  // Ember generated IDs: ember*
  if (/^ember\d+$/.test(id)) {
    return true;
  }

  // Vue scoped style IDs: data-v-*
  if (/^data-v-[0-9a-f]+$/.test(id)) {
    return true;
  }

  // Generic auto-generated patterns
  if (/^(auto|generated|temp|tmp)[-_]/i.test(id)) {
    return true;
  }

  // Long hex strings (likely hashes): 16+ hex chars
  if (/^[0-9a-f]{16,}$/i.test(id)) {
    return true;
  }

  // IDs ending in long random suffixes: foo-a1b2c3d4e5f6
  if (/[-_][0-9a-f]{8,}$/i.test(id)) {
    return true;
  }

  // Very long IDs are suspicious
  if (id.length > MAX_REASONABLE_ID_LENGTH) {
    return true;
  }

  return false;
}

/**
 * Get a positional XPath for an element among matches of a base xpath.
 * Returns `(baseXpath)[n]` if multiple matches, `baseXpath` if unique,
 * or `null` if the target element is not found in the snapshot.
 */
export function getPositionalXPath(
  baseXpath: string,
  target: Element,
  ctx: BrowserCtx,
): string | null {
  const snapshot = ctx.document.evaluate(
    baseXpath,
    ctx.document,
    null,
    XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,
    null,
  );
  for (let i = 0; i < snapshot.snapshotLength; i++) {
    if (snapshot.snapshotItem(i) === target) {
      return snapshot.snapshotLength > 1
        ? `(${baseXpath})[${i + 1}]`
        : baseXpath;
    }
  }
  // Target element not found in snapshot - return null rather than
  // silently returning a potentially non-unique xpath
  return null;
}

/**
 * Resolve an element to a unique XPath using available attributes.
 * Tries attributes in priority order: id -> test-id -> aria-label -> role -> positional.
 * @throws {TypeError} If element is null or undefined
 */
export function resolveElementXPath(
  element: Element,
  ctx: BrowserCtx,
  isUnique: (xpath: string) => boolean,
  opts: ResolveOptions,
): string | null {
  if (!element) {
    throw new TypeError(
      "resolveElementXPath: element cannot be null or undefined",
    );
  }

  const { tag, tryAriaLabel, tryRole, positionalFallback } = opts;
  const base = `//${tag}`;

  // Fetch role once upfront if needed (avoids duplicate getAttribute calls)
  const role = tryAriaLabel || tryRole ? element.getAttribute("role") : null;

  // Try id (skip auto-generated)
  const id = element.id;
  if (id && !isAutoGeneratedId(id)) {
    const xpath = `${base}[@id=${escapeAttr(id)}]`;
    if (isUnique(xpath)) return xpath;
  }

  // Try test-id attributes
  for (const attr of ctx.config.testIdAttrs) {
    const val = element.getAttribute(attr);
    if (val) {
      const xpath = `${base}[@${attr}=${escapeAttr(val)}]`;
      if (isUnique(xpath)) return xpath;
    }
  }

  // Try aria-label
  if (tryAriaLabel) {
    const ariaLabel = element.getAttribute("aria-label");
    if (ariaLabel) {
      // If has role, try role + aria-label combo first (more specific)
      if (tryRole && role) {
        const xpath = `//*[@role=${escapeAttr(role)}][@aria-label=${escapeAttr(ariaLabel)}]`;
        if (isUnique(xpath)) return xpath;
      }
      const xpath = `${base}[@aria-label=${escapeAttr(ariaLabel)}]`;
      if (isUnique(xpath)) return xpath;
    }
  }

  // Try role alone
  if (tryRole && role) {
    const roleXpath = `//*[@role=${escapeAttr(role)}]`;
    if (isUnique(roleXpath)) return roleXpath;
    if (positionalFallback) {
      return getPositionalXPath(roleXpath, element, ctx);
    }
  }

  // Positional fallback by tag
  if (positionalFallback) {
    return getPositionalXPath(base, element, ctx);
  }

  return null;
}
