import type { Strategy } from "./types.js";
import { isAutoGeneratedId, isDynamicUrl } from "./scope-utils.js";
import { escapeAttr, scopeXPath } from "./xpath-utils.js";

/**
 * Build the array of strategies with access to uniqueness checker.
 *
 * Strategies are tried in order. Each returns the XPath if it's unique,
 * or null to try the next strategy.
 */
export function buildStrategies(
  isUnique: (xpath: string) => boolean,
): Strategy[] {
  const strategies: Strategy[] = [
    // Priority 1: Test IDs (most stable, explicitly set for testing)
    {
      name: "testId",
      run: (data, prefix, _ctx) => {
        const attrs = [
          { attr: "data-testid", value: data.dataTestId },
          { attr: "data-test", value: data.dataTest },
          { attr: "data-cy", value: data.dataCy },
          { attr: "data-test-id", value: data.dataTestIdAlt },
          { attr: "data-qa", value: data.dataQa },
        ];
        for (const { attr, value } of attrs) {
          if (value) {
            const xpath = scopeXPath(
              prefix,
              `*[@${attr}=${escapeAttr(value)}]`,
            );
            if (isUnique(xpath)) {
              return xpath;
            }
          }
        }
        return null;
      },
    },

    // Priority 2: ID (skip auto-generated IDs that are unstable)
    {
      name: "id",
      run: (data, prefix, _ctx) => {
        if (!data.id || isAutoGeneratedId(data.id)) {
          return null;
        }
        const xpath = scopeXPath(prefix, `*[@id=${escapeAttr(data.id)}]`);
        if (isUnique(xpath)) {
          return xpath;
        }
        return null;
      },
    },

    // Priority 3: Name attribute
    {
      name: "name",
      run: (data, prefix, _ctx) => {
        if (!data.name) {
          return null;
        }
        const xpath = scopeXPath(
          prefix,
          `${data.tagName}[@name=${escapeAttr(data.name)}]`,
        );
        if (isUnique(xpath)) {
          return xpath;
        }
        return null;
      },
    },

    // Priority 4: For attribute (labels)
    {
      name: "forAttribute",
      run: (data, prefix, _ctx) => {
        if (data.tagName !== "label" || !data.forAttr) {
          return null;
        }
        const xpath = scopeXPath(
          prefix,
          `label[@for=${escapeAttr(data.forAttr)}]`,
        );
        if (isUnique(xpath)) {
          return xpath;
        }
        return null;
      },
    },

    // Priority 5: ARIA Label
    {
      name: "ariaLabel",
      run: (data, prefix, _ctx) => {
        if (!data.ariaLabel) {
          return null;
        }
        const xpath = scopeXPath(
          prefix,
          `${data.tagName}[@aria-label=${escapeAttr(data.ariaLabel)}]`,
        );
        if (isUnique(xpath)) {
          return xpath;
        }
        return null;
      },
    },

    // Priority 6: Title attribute
    {
      name: "title",
      run: (data, prefix, ctx) => {
        if (!data.title || data.title.length >= ctx.config.maxTextLength)
          return null;
        const xpath = scopeXPath(
          prefix,
          `${data.tagName}[@title=${escapeAttr(data.title)}]`,
        );
        if (isUnique(xpath)) {
          return xpath;
        }
        return null;
      },
    },

    // Priority 7: Alt attribute (images)
    {
      name: "alt",
      run: (data, prefix, _ctx) => {
        if (!data.alt) {
          return null;
        }
        const xpath = scopeXPath(
          prefix,
          `${data.tagName}[@alt=${escapeAttr(data.alt)}]`,
        );
        if (isUnique(xpath)) {
          return xpath;
        }
        return null;
      },
    },

    // Priority 8: Href (links only)
    // NOTE: Query strings are allowed since SPAs often use them for stable routes
    // (e.g., /search?q=foo). Only obviously dynamic patterns are excluded.
    // Excludes mailto:/tel: as these contain user-specific data (email addresses, phone numbers)
    {
      name: "href",
      run: (data, prefix, ctx) => {
        if (data.tagName !== "a") {
          return null;
        }
        const href = data.href;
        if (
          !href ||
          href.length < ctx.config.minHrefLength ||
          href.length >= ctx.config.maxHrefLength ||
          href.startsWith("#") ||
          href.startsWith("javascript:") ||
          href.startsWith("data:") ||
          href.startsWith("mailto:") ||
          href.startsWith("tel:") ||
          isDynamicUrl(href)
        ) {
          return null;
        }
        const xpath = scopeXPath(prefix, `a[@href=${escapeAttr(href)}]`);
        if (isUnique(xpath)) {
          return xpath;
        }
        return null;
      },
    },

    // Priority 9: Value attribute (buttons/inputs)
    {
      name: "value",
      run: (data, prefix, ctx) => {
        if (data.tagName !== "button" && data.tagName !== "input") {
          return null;
        }
        if (!data.value || data.value.length >= ctx.config.maxTextLength)
          return null;
        const xpath = scopeXPath(
          prefix,
          `${data.tagName}[@value=${escapeAttr(data.value)}]`,
        );
        if (isUnique(xpath)) {
          return xpath;
        }
        return null;
      },
    },

    // Priority 10: Placeholder attribute (inputs/textareas)
    {
      name: "placeholder",
      run: (data, prefix, ctx) => {
        if (data.tagName !== "input" && data.tagName !== "textarea")
          return null;
        if (
          !data.placeholder ||
          data.placeholder.length >= ctx.config.maxTextLength
        )
          return null;
        const xpath = scopeXPath(
          prefix,
          `${data.tagName}[@placeholder=${escapeAttr(data.placeholder)}]`,
        );
        if (isUnique(xpath)) {
          return xpath;
        }
        return null;
      },
    },

    // Priority 11: Descendant image alt (containers with img children)
    // Tries all descendant image alts until one produces a unique selector
    {
      name: "descendantImgAlt",
      run: (data, prefix, ctx) => {
        if (!ctx.config.containerTags.includes(data.tagName)) {
          return null;
        }
        if (data.descendantImgAlts.length === 0) {
          return null;
        }
        for (const alt of data.descendantImgAlts) {
          const xpath = scopeXPath(
            prefix,
            `${data.tagName}[.//img[@alt=${escapeAttr(alt)}]]`,
          );
          if (isUnique(xpath)) {
            return xpath;
          }
        }
        return null;
      },
    },

    // Priority 12: Text content
    {
      name: "textContent",
      run: (data, prefix, ctx) => {
        if (!ctx.config.textTags.includes(data.tagName)) {
          return null;
        }
        if (
          !data.text ||
          data.textLength <= 0 ||
          data.textLength >= ctx.config.maxTextLength
        )
          return null;
        const xpath = scopeXPath(
          prefix,
          `${data.tagName}[normalize-space(.)=${escapeAttr(data.text)}]`,
        );
        if (isUnique(xpath)) {
          return xpath;
        }
        return null;
      },
    },

    // Priority 13: Role + attribute (explicit roles only, last resort)
    // NOTE: This strategy only works with explicit role="..." attributes.
    // It does NOT compute implicit ARIA roles (e.g., button tag has implicit role="button").
    // As a result, this is effectively a last-ditch strategy for elements that:
    // 1. Have an explicit role attribute AND
    // 2. Have either aria-label or text content for disambiguation
    // Confidence is lower (0.4) because role attributes can match many elements.
    {
      name: "role",
      run: (data, prefix, ctx) => {
        // Early exit: need role AND at least one disambiguator (ariaLabel or valid text)
        const hasValidText =
          data.text &&
          data.textLength > 0 &&
          data.textLength < ctx.config.maxTextLength;
        if (!data.role || (!data.ariaLabel && !hasValidText)) {
          return null;
        }

        const roleEscaped = escapeAttr(data.role);

        // Role + aria-label: try tag first, then wildcard
        if (data.ariaLabel) {
          const ariaEscaped = escapeAttr(data.ariaLabel);
          // Prefer: button[@role="tab"][@aria-label="Settings"]
          const tagXpath = scopeXPath(
            prefix,
            `${data.tagName}[@role=${roleEscaped}][@aria-label=${ariaEscaped}]`,
          );
          if (isUnique(tagXpath)) {
            return tagXpath;
          }
          // Fallback: *[@role="tab"][@aria-label="Settings"]
          const wildXpath = scopeXPath(
            prefix,
            `*[@role=${roleEscaped}][@aria-label=${ariaEscaped}]`,
          );
          if (isUnique(wildXpath)) {
            return wildXpath;
          }
        }

        // Role + text: try tag first, then wildcard
        if (hasValidText) {
          const textEscaped = escapeAttr(data.text!);
          // Prefer: li[@role="option"][normalize-space(.)="Item"]
          const tagXpath = scopeXPath(
            prefix,
            `${data.tagName}[@role=${roleEscaped}][normalize-space(.)=${textEscaped}]`,
          );
          if (isUnique(tagXpath)) {
            return tagXpath;
          }
          // Fallback: *[@role="option"][normalize-space(.)="Item"]
          const wildXpath = scopeXPath(
            prefix,
            `*[@role=${roleEscaped}][normalize-space(.)=${textEscaped}]`,
          );
          if (isUnique(wildXpath)) {
            return wildXpath;
          }
        }

        return null;
      },
    },
  ];

  return strategies;
}
