/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { BamlRuntime, FunctionResult, BamlCtxManager, Image, Audio, Pdf, Video, FunctionLog,
HTTPRequest } from "@boundaryml/baml"
import { toBamlError, BamlStream, BamlAbortError, Collector, ClientRegistry } from "@boundaryml/baml"
import type { Checked, Check, RecursivePartialNull as MovedRecursivePartialNull } from "./types"
import type { partial_types } from "./partial_types"
import type * as types from "./types"
import type {ActionType, ExplorationPriority, GraphPathInfo, GraphSummary, PlaywrightTestCode, SemanticElementAnalysis, SemanticElementBatchResult, SemanticElementKind, TestCase, TestPriority, TestStep} from "./types"
import type TypeBuilder from "./type_builder"
import { AsyncHttpRequest, AsyncHttpStreamRequest } from "./async_request"
import { LlmResponseParser, LlmStreamParser } from "./parser"
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX,
DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"
import type * as events from "./events"

/**
* @deprecated Use RecursivePartialNull from 'baml_client/types' instead.
*/
export type RecursivePartialNull<T> = MovedRecursivePartialNull<T>

    type TickReason = "Unknown";

    type BamlCallOptions<WatchersT = never> = {
    tb?: TypeBuilder
    clientRegistry?: ClientRegistry
    client?: string
    collector?: Collector | Collector[]
    env?: Record<string, string | undefined>
      tags?: Record<string, string>
        signal?: AbortSignal
        onTick?: (reason: TickReason, log: FunctionLog | null) => void
        watchers?: WatchersT
        }

        export class BamlAsyncClient {
        private runtime: BamlRuntime
        private ctxManager: BamlCtxManager
        private streamClient: BamlStreamClient
        private httpRequest: AsyncHttpRequest
        private httpStreamRequest: AsyncHttpStreamRequest
        private llmResponseParser: LlmResponseParser
        private llmStreamParser: LlmStreamParser
        private bamlOptions: BamlCallOptions

        constructor(runtime: BamlRuntime, ctxManager: BamlCtxManager, bamlOptions?: BamlCallOptions) {
        this.runtime = runtime
        this.ctxManager = ctxManager
        this.streamClient = new BamlStreamClient(runtime, ctxManager, bamlOptions)
        this.httpRequest = new AsyncHttpRequest(runtime, ctxManager)
        this.httpStreamRequest = new AsyncHttpStreamRequest(runtime, ctxManager)
        this.llmResponseParser = new LlmResponseParser(runtime, ctxManager)
        this.llmStreamParser = new LlmStreamParser(runtime, ctxManager)
        this.bamlOptions = bamlOptions || {}
        }

        withOptions(bamlOptions: BamlCallOptions) {
        return new BamlAsyncClient(this.runtime, this.ctxManager, bamlOptions)
        }

        get stream() {
        return this.streamClient
        }

        get request() {
        return this.httpRequest
        }

        get streamRequest() {
        return this.httpStreamRequest
        }

        get parse() {
        return this.llmResponseParser
        }

        get parseStream() {
        return this.llmStreamParser
        }

        
        async AnalyzeElements(
        url: string,screenshotBase64: Image,elementsJson: string,legendDescription: string,
        __baml_options__?: BamlCallOptions<never>
        ): Promise<types.SemanticElementBatchResult> {
          try {
          const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
          const __signal__ = __options__.signal;

          if (__signal__?.aborted) {
          throw new BamlAbortError('Operation was aborted', __signal__.reason);
          }

          // Check if onTick is provided - route through streaming if so
          if (__options__.onTick) {
          const __stream__ = this.stream.AnalyzeElements(
          url,screenshotBase64,elementsJson,legendDescription,
          __baml_options__
          );

          return await __stream__.getFinalResponse();
          }

          const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
          [__options__.collector]) : [];
          const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
          const __env__: Record<string, string> = Object.fromEntries(
            Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
            );

            // Resolve client option to clientRegistry (client takes precedence)
            let __clientRegistry__ = __options__.clientRegistry;
            if (__options__.client) {
              __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
              __clientRegistry__.setPrimary(__options__.client);
            }

            const __raw__ = await this.runtime.callFunction(
            "AnalyzeElements",
            {
            "url": url,"screenshotBase64": screenshotBase64,"elementsJson": elementsJson,"legendDescription": legendDescription
            },
            this.ctxManager.cloneContext(),
            __options__.tb?.__tb(),
            __clientRegistry__,
            __collector__,
            __options__.tags || {},
            __env__,
            __signal__,
            __options__.watchers,
            )
            return __raw__.parsed(false) as types.SemanticElementBatchResult
            } catch (error) {
            throw toBamlError(error);
            }
            }
            
        async GeneratePlaywrightCode(
        testCases: types.TestCase[],baseUrl: string,projectName: string,
        __baml_options__?: BamlCallOptions<never>
        ): Promise<types.PlaywrightTestCode[]> {
          try {
          const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
          const __signal__ = __options__.signal;

          if (__signal__?.aborted) {
          throw new BamlAbortError('Operation was aborted', __signal__.reason);
          }

          // Check if onTick is provided - route through streaming if so
          if (__options__.onTick) {
          const __stream__ = this.stream.GeneratePlaywrightCode(
          testCases,baseUrl,projectName,
          __baml_options__
          );

          return await __stream__.getFinalResponse();
          }

          const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
          [__options__.collector]) : [];
          const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
          const __env__: Record<string, string> = Object.fromEntries(
            Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
            );

            // Resolve client option to clientRegistry (client takes precedence)
            let __clientRegistry__ = __options__.clientRegistry;
            if (__options__.client) {
              __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
              __clientRegistry__.setPrimary(__options__.client);
            }

            const __raw__ = await this.runtime.callFunction(
            "GeneratePlaywrightCode",
            {
            "testCases": testCases,"baseUrl": baseUrl,"projectName": projectName
            },
            this.ctxManager.cloneContext(),
            __options__.tb?.__tb(),
            __clientRegistry__,
            __collector__,
            __options__.tags || {},
            __env__,
            __signal__,
            __options__.watchers,
            )
            return __raw__.parsed(false) as types.PlaywrightTestCode[]
            } catch (error) {
            throw toBamlError(error);
            }
            }
            
        async GeneratePlaywrightCodeSingle(
        testCase: types.TestCase,baseUrl: string,
        __baml_options__?: BamlCallOptions<never>
        ): Promise<types.PlaywrightTestCode> {
          try {
          const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
          const __signal__ = __options__.signal;

          if (__signal__?.aborted) {
          throw new BamlAbortError('Operation was aborted', __signal__.reason);
          }

          // Check if onTick is provided - route through streaming if so
          if (__options__.onTick) {
          const __stream__ = this.stream.GeneratePlaywrightCodeSingle(
          testCase,baseUrl,
          __baml_options__
          );

          return await __stream__.getFinalResponse();
          }

          const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
          [__options__.collector]) : [];
          const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
          const __env__: Record<string, string> = Object.fromEntries(
            Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
            );

            // Resolve client option to clientRegistry (client takes precedence)
            let __clientRegistry__ = __options__.clientRegistry;
            if (__options__.client) {
              __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
              __clientRegistry__.setPrimary(__options__.client);
            }

            const __raw__ = await this.runtime.callFunction(
            "GeneratePlaywrightCodeSingle",
            {
            "testCase": testCase,"baseUrl": baseUrl
            },
            this.ctxManager.cloneContext(),
            __options__.tb?.__tb(),
            __clientRegistry__,
            __collector__,
            __options__.tags || {},
            __env__,
            __signal__,
            __options__.watchers,
            )
            return __raw__.parsed(false) as types.PlaywrightTestCode
            } catch (error) {
            throw toBamlError(error);
            }
            }
            
        async GenerateTestCasesFromGraph(
        graphSummary: types.GraphSummary,identifiedPaths: types.GraphPathInfo[],baseUrl: string,
        __baml_options__?: BamlCallOptions<never>
        ): Promise<types.TestCase[]> {
          try {
          const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
          const __signal__ = __options__.signal;

          if (__signal__?.aborted) {
          throw new BamlAbortError('Operation was aborted', __signal__.reason);
          }

          // Check if onTick is provided - route through streaming if so
          if (__options__.onTick) {
          const __stream__ = this.stream.GenerateTestCasesFromGraph(
          graphSummary,identifiedPaths,baseUrl,
          __baml_options__
          );

          return await __stream__.getFinalResponse();
          }

          const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
          [__options__.collector]) : [];
          const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
          const __env__: Record<string, string> = Object.fromEntries(
            Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
            );

            // Resolve client option to clientRegistry (client takes precedence)
            let __clientRegistry__ = __options__.clientRegistry;
            if (__options__.client) {
              __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
              __clientRegistry__.setPrimary(__options__.client);
            }

            const __raw__ = await this.runtime.callFunction(
            "GenerateTestCasesFromGraph",
            {
            "graphSummary": graphSummary,"identifiedPaths": identifiedPaths,"baseUrl": baseUrl
            },
            this.ctxManager.cloneContext(),
            __options__.tb?.__tb(),
            __clientRegistry__,
            __collector__,
            __options__.tags || {},
            __env__,
            __signal__,
            __options__.watchers,
            )
            return __raw__.parsed(false) as types.TestCase[]
            } catch (error) {
            throw toBamlError(error);
            }
            }
            
            }

            class BamlStreamClient {
            private runtime: BamlRuntime
            private ctxManager: BamlCtxManager
            private bamlOptions: BamlCallOptions

            constructor(runtime: BamlRuntime, ctxManager: BamlCtxManager, bamlOptions?: BamlCallOptions) {
            this.runtime = runtime
            this.ctxManager = ctxManager
            this.bamlOptions = bamlOptions || {}
            }

            
            AnalyzeElements(
            url: string,screenshotBase64: Image,elementsJson: string,legendDescription: string,
            __baml_options__?: BamlCallOptions<never>
            ): BamlStream<partial_types.SemanticElementBatchResult, types.SemanticElementBatchResult>
              {
              try {
              const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
              const __signal__ = __options__.signal;

              if (__signal__?.aborted) {
              throw new BamlAbortError('Operation was aborted', __signal__.reason);
              }

              let __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
              [__options__.collector]) : [];

              let __onTickWrapper__: (() => void) | undefined;

              // Create collector and wrap onTick if provided
              if (__options__.onTick) {
              const __tickCollector__ = new Collector("on-tick-collector");
              __collector__ = [...__collector__, __tickCollector__];

              __onTickWrapper__ = () => {
              const __log__ = __tickCollector__.last;
              if (__log__) {
              try {
              __options__.onTick!("Unknown", __log__);
              } catch (error) {
              console.error("Error in onTick callback for AnalyzeElements", error);
              }
              }
              };
              }

              const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
              const __env__: Record<string, string> = Object.fromEntries(
                Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
                );

                // Resolve client option to clientRegistry (client takes precedence)
                let __clientRegistry__ = __options__.clientRegistry;
                if (__options__.client) {
                  __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
                  __clientRegistry__.setPrimary(__options__.client);
                }

                const __raw__ = this.runtime.streamFunction(
                "AnalyzeElements",
                {
                "url": url,"screenshotBase64": screenshotBase64,"elementsJson": elementsJson,"legendDescription": legendDescription
                },
                undefined,
                this.ctxManager.cloneContext(),
                __options__.tb?.__tb(),
                __clientRegistry__,
                __collector__,
                __options__.tags || {},
                __env__,
                __signal__,
                __onTickWrapper__,
                )
                return new BamlStream<partial_types.SemanticElementBatchResult, types.SemanticElementBatchResult>(
                  __raw__,
                  (a): partial_types.SemanticElementBatchResult => a,
                  (a): types.SemanticElementBatchResult => a,
                  this.ctxManager.cloneContext(),
                  __options__.signal,
                  )
                  } catch (error) {
                  throw toBamlError(error);
                  }
                  }
                  
            GeneratePlaywrightCode(
            testCases: types.TestCase[],baseUrl: string,projectName: string,
            __baml_options__?: BamlCallOptions<never>
            ): BamlStream<partial_types.PlaywrightTestCode[], types.PlaywrightTestCode[]>
              {
              try {
              const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
              const __signal__ = __options__.signal;

              if (__signal__?.aborted) {
              throw new BamlAbortError('Operation was aborted', __signal__.reason);
              }

              let __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
              [__options__.collector]) : [];

              let __onTickWrapper__: (() => void) | undefined;

              // Create collector and wrap onTick if provided
              if (__options__.onTick) {
              const __tickCollector__ = new Collector("on-tick-collector");
              __collector__ = [...__collector__, __tickCollector__];

              __onTickWrapper__ = () => {
              const __log__ = __tickCollector__.last;
              if (__log__) {
              try {
              __options__.onTick!("Unknown", __log__);
              } catch (error) {
              console.error("Error in onTick callback for GeneratePlaywrightCode", error);
              }
              }
              };
              }

              const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
              const __env__: Record<string, string> = Object.fromEntries(
                Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
                );

                // Resolve client option to clientRegistry (client takes precedence)
                let __clientRegistry__ = __options__.clientRegistry;
                if (__options__.client) {
                  __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
                  __clientRegistry__.setPrimary(__options__.client);
                }

                const __raw__ = this.runtime.streamFunction(
                "GeneratePlaywrightCode",
                {
                "testCases": testCases,"baseUrl": baseUrl,"projectName": projectName
                },
                undefined,
                this.ctxManager.cloneContext(),
                __options__.tb?.__tb(),
                __clientRegistry__,
                __collector__,
                __options__.tags || {},
                __env__,
                __signal__,
                __onTickWrapper__,
                )
                return new BamlStream<partial_types.PlaywrightTestCode[], types.PlaywrightTestCode[]>(
                  __raw__,
                  (a): partial_types.PlaywrightTestCode[] => a,
                  (a): types.PlaywrightTestCode[] => a,
                  this.ctxManager.cloneContext(),
                  __options__.signal,
                  )
                  } catch (error) {
                  throw toBamlError(error);
                  }
                  }
                  
            GeneratePlaywrightCodeSingle(
            testCase: types.TestCase,baseUrl: string,
            __baml_options__?: BamlCallOptions<never>
            ): BamlStream<partial_types.PlaywrightTestCode, types.PlaywrightTestCode>
              {
              try {
              const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
              const __signal__ = __options__.signal;

              if (__signal__?.aborted) {
              throw new BamlAbortError('Operation was aborted', __signal__.reason);
              }

              let __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
              [__options__.collector]) : [];

              let __onTickWrapper__: (() => void) | undefined;

              // Create collector and wrap onTick if provided
              if (__options__.onTick) {
              const __tickCollector__ = new Collector("on-tick-collector");
              __collector__ = [...__collector__, __tickCollector__];

              __onTickWrapper__ = () => {
              const __log__ = __tickCollector__.last;
              if (__log__) {
              try {
              __options__.onTick!("Unknown", __log__);
              } catch (error) {
              console.error("Error in onTick callback for GeneratePlaywrightCodeSingle", error);
              }
              }
              };
              }

              const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
              const __env__: Record<string, string> = Object.fromEntries(
                Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
                );

                // Resolve client option to clientRegistry (client takes precedence)
                let __clientRegistry__ = __options__.clientRegistry;
                if (__options__.client) {
                  __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
                  __clientRegistry__.setPrimary(__options__.client);
                }

                const __raw__ = this.runtime.streamFunction(
                "GeneratePlaywrightCodeSingle",
                {
                "testCase": testCase,"baseUrl": baseUrl
                },
                undefined,
                this.ctxManager.cloneContext(),
                __options__.tb?.__tb(),
                __clientRegistry__,
                __collector__,
                __options__.tags || {},
                __env__,
                __signal__,
                __onTickWrapper__,
                )
                return new BamlStream<partial_types.PlaywrightTestCode, types.PlaywrightTestCode>(
                  __raw__,
                  (a): partial_types.PlaywrightTestCode => a,
                  (a): types.PlaywrightTestCode => a,
                  this.ctxManager.cloneContext(),
                  __options__.signal,
                  )
                  } catch (error) {
                  throw toBamlError(error);
                  }
                  }
                  
            GenerateTestCasesFromGraph(
            graphSummary: types.GraphSummary,identifiedPaths: types.GraphPathInfo[],baseUrl: string,
            __baml_options__?: BamlCallOptions<never>
            ): BamlStream<partial_types.TestCase[], types.TestCase[]>
              {
              try {
              const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
              const __signal__ = __options__.signal;

              if (__signal__?.aborted) {
              throw new BamlAbortError('Operation was aborted', __signal__.reason);
              }

              let __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
              [__options__.collector]) : [];

              let __onTickWrapper__: (() => void) | undefined;

              // Create collector and wrap onTick if provided
              if (__options__.onTick) {
              const __tickCollector__ = new Collector("on-tick-collector");
              __collector__ = [...__collector__, __tickCollector__];

              __onTickWrapper__ = () => {
              const __log__ = __tickCollector__.last;
              if (__log__) {
              try {
              __options__.onTick!("Unknown", __log__);
              } catch (error) {
              console.error("Error in onTick callback for GenerateTestCasesFromGraph", error);
              }
              }
              };
              }

              const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
              const __env__: Record<string, string> = Object.fromEntries(
                Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
                );

                // Resolve client option to clientRegistry (client takes precedence)
                let __clientRegistry__ = __options__.clientRegistry;
                if (__options__.client) {
                  __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
                  __clientRegistry__.setPrimary(__options__.client);
                }

                const __raw__ = this.runtime.streamFunction(
                "GenerateTestCasesFromGraph",
                {
                "graphSummary": graphSummary,"identifiedPaths": identifiedPaths,"baseUrl": baseUrl
                },
                undefined,
                this.ctxManager.cloneContext(),
                __options__.tb?.__tb(),
                __clientRegistry__,
                __collector__,
                __options__.tags || {},
                __env__,
                __signal__,
                __onTickWrapper__,
                )
                return new BamlStream<partial_types.TestCase[], types.TestCase[]>(
                  __raw__,
                  (a): partial_types.TestCase[] => a,
                  (a): types.TestCase[] => a,
                  this.ctxManager.cloneContext(),
                  __options__.signal,
                  )
                  } catch (error) {
                  throw toBamlError(error);
                  }
                  }
                  
                  }

                  export const b = new BamlAsyncClient(DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME,
                  DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX)