/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { BamlRuntime, BamlCtxManager, Image, Audio, Pdf, Video, FunctionLog } from
"@boundaryml/baml"
import { toBamlError, HTTPRequest, ClientRegistry } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type * as types from "./types"
import type {ActionType, ExplorationPriority, GraphPathInfo, GraphSummary, PlaywrightTestCode, SemanticElementAnalysis, SemanticElementBatchResult, SemanticElementKind, TestCase, TestPriority, TestStep} from "./types"
import type TypeBuilder from "./type_builder"
import type * as events from "./events"

type TickReason = "Unknown";

type BamlCallOptions<EventsT = never> = {
tb?: TypeBuilder
clientRegistry?: ClientRegistry
client?: string
env?: Record<string, string | undefined>
  onTick?: (reason: TickReason, log: FunctionLog | null) => void
  events?: EventsT
  }

  export class AsyncHttpRequest {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
  async AnalyzeElements(
  url: string,screenshotBase64: Image,elementsJson: string,legendDescription: string,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "AnalyzeElements",
      {
      "url": url,"screenshotBase64": screenshotBase64,"elementsJson": elementsJson,"legendDescription": legendDescription
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async GeneratePlaywrightCode(
  testCases: types.TestCase[],baseUrl: string,projectName: string,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "GeneratePlaywrightCode",
      {
      "testCases": testCases,"baseUrl": baseUrl,"projectName": projectName
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async GeneratePlaywrightCodeSingle(
  testCase: types.TestCase,baseUrl: string,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "GeneratePlaywrightCodeSingle",
      {
      "testCase": testCase,"baseUrl": baseUrl
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async GenerateTestCasesFromGraph(
  graphSummary: types.GraphSummary,identifiedPaths: types.GraphPathInfo[],baseUrl: string,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "GenerateTestCasesFromGraph",
      {
      "graphSummary": graphSummary,"identifiedPaths": identifiedPaths,"baseUrl": baseUrl
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
      }

      export class AsyncHttpStreamRequest {
      constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

      
      async AnalyzeElements(
      url: string,screenshotBase64: Image,elementsJson: string,legendDescription: string,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "AnalyzeElements",
          {
          "url": url,"screenshotBase64": screenshotBase64,"elementsJson": elementsJson,"legendDescription": legendDescription
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async GeneratePlaywrightCode(
      testCases: types.TestCase[],baseUrl: string,projectName: string,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "GeneratePlaywrightCode",
          {
          "testCases": testCases,"baseUrl": baseUrl,"projectName": projectName
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async GeneratePlaywrightCodeSingle(
      testCase: types.TestCase,baseUrl: string,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "GeneratePlaywrightCodeSingle",
          {
          "testCase": testCase,"baseUrl": baseUrl
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async GenerateTestCasesFromGraph(
      graphSummary: types.GraphSummary,identifiedPaths: types.GraphPathInfo[],baseUrl: string,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "GenerateTestCasesFromGraph",
          {
          "graphSummary": graphSummary,"identifiedPaths": identifiedPaths,"baseUrl": baseUrl
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
          }