/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

const fileMap = {
  
  "clients.baml": "// BAML client configuration for vibetest\n// Docs: https://docs.boundaryml.com\n\ngenerator target {\n  output_type \"typescript\"\n  output_dir \"../src\"\n  version \"0.218.0\"\n}\n\nclient<llm> Anthropic {\n  provider anthropic\n  options {\n    model claude-sonnet-4-20250514\n    api_key env.ANTHROPIC_API_KEY\n  }\n}\n\nclient<llm> OpenAI {\n  provider openai\n  options {\n    model gpt-4o\n    api_key env.OPENAI_API_KEY\n  }\n}\n",
}
export const getBamlFiles = () => {
    return fileMap;
}