/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  ActionType,  ExplorationPriority,  GraphPathInfo,  GraphSummary,  PlaywrightTestCode,  SemanticElementAnalysis,  SemanticElementBatchResult,  SemanticElementKind,  TestCase,  TestPriority,  TestStep } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface GraphPathInfo {
      name?: string | null
      urls: string[]
      score?: number | null
      category?: string | null
      hasAuthentication?: boolean | null
      hasCriticalActions?: boolean | null
      keyElements: string[]
    }
    export interface GraphSummary {
      totalPages?: number | null
      maxDepth?: number | null
      hubPageUrls: string[]
      clusterSummaries: string[]
      topPaths: GraphPathInfo[]
      unexploredCategories: string[]
    }
    export interface PlaywrightTestCode {
      filename?: string | null
      code?: string | null
      imports: string[]
      fixtures: string[]
    }
    export interface SemanticElementAnalysis {
      elementId?: string | null
      semanticKind?: types.SemanticElementKind | null
      domainIntent?: string | null
      importanceScore?: number | null
      explorationPriority?: types.ExplorationPriority | null
      reasoning?: string | null
    }
    export interface SemanticElementBatchResult {
      elements: SemanticElementAnalysis[]
    }
    export interface TestCase {
      name?: string | null
      description?: string | null
      priority?: types.TestPriority | null
      tags: string[]
      steps: TestStep[]
      preconditions: string[]
      postconditions: string[]
    }
    export interface TestStep {
      action?: types.ActionType | null
      target?: string | null
      value?: string | null
      description?: string | null
      order?: number | null
    }
}