/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import { FieldType } from '@boundaryml/baml/native'
import { TypeBuilder as _TypeBuilder, EnumBuilder, EnumViewer, ClassBuilder, ClassViewer } from '@boundaryml/baml/type_builder'
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"

export { FieldType, EnumBuilder, ClassBuilder }

export default class TypeBuilder {
    private tb: _TypeBuilder;
    
    GraphPathInfo: ClassViewer<'GraphPathInfo', "name" | "urls" | "score" | "category" | "hasAuthentication" | "hasCriticalActions" | "keyElements">;
    
    GraphSummary: ClassViewer<'GraphSummary', "totalPages" | "maxDepth" | "hubPageUrls" | "clusterSummaries" | "topPaths" | "unexploredCategories">;
    
    PlaywrightTestCode: ClassViewer<'PlaywrightTestCode', "filename" | "code" | "imports" | "fixtures">;
    
    SemanticElementAnalysis: ClassViewer<'SemanticElementAnalysis', "elementId" | "semanticKind" | "domainIntent" | "importanceScore" | "explorationPriority" | "reasoning">;
    
    SemanticElementBatchResult: ClassViewer<'SemanticElementBatchResult', "elements">;
    
    TestCase: ClassViewer<'TestCase', "name" | "description" | "priority" | "tags" | "steps" | "preconditions" | "postconditions">;
    
    TestStep: ClassViewer<'TestStep', "action" | "target" | "value" | "description" | "order">;
    
    
    ActionType: EnumViewer<'ActionType', "NAVIGATE" | "CLICK" | "TYPE" | "SELECT" | "WAIT" | "ASSERT_TEXT" | "ASSERT_VISIBLE" | "ASSERT_URL" | "ASSERT_ATTRIBUTE" | "SCREENSHOT">;
    
    ExplorationPriority: EnumViewer<'ExplorationPriority', "HIGH" | "MEDIUM" | "LOW" | "IGNORE">;
    
    SemanticElementKind: EnumViewer<'SemanticElementKind', "PRIMARY_CALL_TO_ACTION" | "SECONDARY_ACTION" | "NAVIGATION" | "FORM_FIELD" | "SEARCH" | "FILTER_OR_SORT" | "PAGINATION" | "DANGEROUS_ACTION" | "DISMISS_OR_CLOSE" | "DECORATIVE_OR_LOW_VALUE" | "OTHER">;
    
    TestPriority: EnumViewer<'TestPriority', "CRITICAL" | "HIGH" | "MEDIUM" | "LOW">;
    

    constructor() {
        this.tb = new _TypeBuilder({
          classes: new Set([
            "GraphPathInfo","GraphSummary","PlaywrightTestCode","SemanticElementAnalysis","SemanticElementBatchResult","TestCase","TestStep",
          ]),
          enums: new Set([
            "ActionType","ExplorationPriority","SemanticElementKind","TestPriority",
          ]),
          runtime: DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME
        });
        
        this.GraphPathInfo = this.tb.classViewer("GraphPathInfo", [
          "name","urls","score","category","hasAuthentication","hasCriticalActions","keyElements",
        ]);
        
        this.GraphSummary = this.tb.classViewer("GraphSummary", [
          "totalPages","maxDepth","hubPageUrls","clusterSummaries","topPaths","unexploredCategories",
        ]);
        
        this.PlaywrightTestCode = this.tb.classViewer("PlaywrightTestCode", [
          "filename","code","imports","fixtures",
        ]);
        
        this.SemanticElementAnalysis = this.tb.classViewer("SemanticElementAnalysis", [
          "elementId","semanticKind","domainIntent","importanceScore","explorationPriority","reasoning",
        ]);
        
        this.SemanticElementBatchResult = this.tb.classViewer("SemanticElementBatchResult", [
          "elements",
        ]);
        
        this.TestCase = this.tb.classViewer("TestCase", [
          "name","description","priority","tags","steps","preconditions","postconditions",
        ]);
        
        this.TestStep = this.tb.classViewer("TestStep", [
          "action","target","value","description","order",
        ]);
        
        
        this.ActionType = this.tb.enumViewer("ActionType", [
          "NAVIGATE","CLICK","TYPE","SELECT","WAIT","ASSERT_TEXT","ASSERT_VISIBLE","ASSERT_URL","ASSERT_ATTRIBUTE","SCREENSHOT",
        ]);
        
        this.ExplorationPriority = this.tb.enumViewer("ExplorationPriority", [
          "HIGH","MEDIUM","LOW","IGNORE",
        ]);
        
        this.SemanticElementKind = this.tb.enumViewer("SemanticElementKind", [
          "PRIMARY_CALL_TO_ACTION","SECONDARY_ACTION","NAVIGATION","FORM_FIELD","SEARCH","FILTER_OR_SORT","PAGINATION","DANGEROUS_ACTION","DISMISS_OR_CLOSE","DECORATIVE_OR_LOW_VALUE","OTHER",
        ]);
        
        this.TestPriority = this.tb.enumViewer("TestPriority", [
          "CRITICAL","HIGH","MEDIUM","LOW",
        ]);
        
    }

    reset(): void {
        this.tb.reset();
        // TODO: This should happen in Rust. Problem is, when we construct the
        // typebuilder we instantiate class builders once and it seems to make
        // a JS copy, bypassing the Rust side? In Python however, every time we
        // access a class builder with @property, we get a new instance that
        // wraps over the Rust type builder, so we only need to call tb.reset().
        // In JS it's not possible unless we refactor the way class builders are
        // accessed.
        
    }

    __tb() {
      return this.tb._tb();
    }

    string(): FieldType {
        return this.tb.string()
    }

    literalString(value: string): FieldType {
        return this.tb.literalString(value)
    }

    literalInt(value: number): FieldType {
        return this.tb.literalInt(value)
    }

    literalBool(value: boolean): FieldType {
        return this.tb.literalBool(value)
    }

    int(): FieldType {
        return this.tb.int()
    }

    float(): FieldType {
        return this.tb.float()
    }

    bool(): FieldType {
        return this.tb.bool()
    }

    list(type: FieldType): FieldType {
        return this.tb.list(type)
    }

    null(): FieldType {
        return this.tb.null()
    }

    map(key: FieldType, value: FieldType): FieldType {
        return this.tb.map(key, value)
    }

    union(types: FieldType[]): FieldType {
        return this.tb.union(types)
    }

    addClass<Name extends string>(name: Name): ClassBuilder<Name> {
        return this.tb.addClass(name);
    }

    addEnum<Name extends string>(name: Name): EnumBuilder<Name> {
        return this.tb.addEnum(name);
    }

    addBaml(baml: string): void {
        this.tb.addBaml(baml);
    }
}