/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}

export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export enum ActionType {
  NAVIGATE = "NAVIGATE",
  CLICK = "CLICK",
  TYPE = "TYPE",
  SELECT = "SELECT",
  WAIT = "WAIT",
  ASSERT_TEXT = "ASSERT_TEXT",
  ASSERT_VISIBLE = "ASSERT_VISIBLE",
  ASSERT_URL = "ASSERT_URL",
  ASSERT_ATTRIBUTE = "ASSERT_ATTRIBUTE",
  SCREENSHOT = "SCREENSHOT",
}

export enum ExplorationPriority {
  HIGH = "HIGH",
  MEDIUM = "MEDIUM",
  LOW = "LOW",
  IGNORE = "IGNORE",
}

export enum SemanticElementKind {
  PRIMARY_CALL_TO_ACTION = "PRIMARY_CALL_TO_ACTION",
  SECONDARY_ACTION = "SECONDARY_ACTION",
  NAVIGATION = "NAVIGATION",
  FORM_FIELD = "FORM_FIELD",
  SEARCH = "SEARCH",
  FILTER_OR_SORT = "FILTER_OR_SORT",
  PAGINATION = "PAGINATION",
  DANGEROUS_ACTION = "DANGEROUS_ACTION",
  DISMISS_OR_CLOSE = "DISMISS_OR_CLOSE",
  DECORATIVE_OR_LOW_VALUE = "DECORATIVE_OR_LOW_VALUE",
  OTHER = "OTHER",
}

export enum TestPriority {
  CRITICAL = "CRITICAL",
  HIGH = "HIGH",
  MEDIUM = "MEDIUM",
  LOW = "LOW",
}

export interface GraphPathInfo {
  name: string
  urls: string[]
  score: number
  category: string
  hasAuthentication: boolean
  hasCriticalActions: boolean
  keyElements: string[]
  
}

export interface GraphSummary {
  totalPages: number
  maxDepth: number
  hubPageUrls: string[]
  clusterSummaries: string[]
  topPaths: GraphPathInfo[]
  unexploredCategories: string[]
  
}

export interface PlaywrightTestCode {
  filename: string
  code: string
  imports: string[]
  fixtures: string[]
  
}

export interface SemanticElementAnalysis {
  elementId: string
  semanticKind: SemanticElementKind
  domainIntent: string
  importanceScore: number
  explorationPriority: ExplorationPriority
  reasoning?: string | null
  
}

export interface SemanticElementBatchResult {
  elements: SemanticElementAnalysis[]
  
}

export interface TestCase {
  name: string
  description: string
  priority: TestPriority
  tags: string[]
  steps: TestStep[]
  preconditions: string[]
  postconditions: string[]
  
}

export interface TestStep {
  action: ActionType
  target?: string | null
  value?: string | null
  description: string
  order: number
  
}
